name: tsp
use_cuda: True
cuda_device_num: 0
logger: no_logger # [wandb, no_logger]
val_filename: data/tsp100_val.pkl
load_checkpoint: weights/ELG_vary_N.pt
# load_checkpoint:
training: joint # [joint, only_local]
seed: 924
params:
  problem_size: 500
  fixed_size: varying # [small, varying]
  multiple_width: 100
  keep_num: 20
  alg: risk_seeking # [pomo, risk_seeking]
  start_steps: 0
  train_steps: 250000
  inner_steps: 1
  train_batch_size: 120
  test_size: 1000
  test_batch_size: 1000
  learning_rate: 0.0001
  log_step: 10000
  aug_factor: 1
model_params:
  ensemble: learn # [learn, no]
  ensemble_size: 1
  encoder_mask: False
  penalty: -1
  local_size: [50]
  embedding_dim: 128
  encoder_layer_num: 6
  head_num: 8
  qkv_dim: 16
  logit_clipping: 50
  ff_hidden_dim: 512