name: CVRP
use_cuda: True
cuda_device_num: 0
logger: no_logger # [wandb, no_logger]
val_filename: data/vrp100_val.pkl
test_filename: data/cvrp200_explosion.pkl
vrplib_set: X     # [XXL, X]
load_checkpoint: weights/ELG.pt
# load_checkpoint: 
training: joint # [joint, only_local]
seed: 924
params:
  problem_size: 500
  size: varying     # [small, varying]
  multiple_width: 100     # The number of multiple rollouts
  keep_num: 20      # xi in the paper
  alg: risk_seeking     # [pomo, risk_seeking]
  start_steps: 0
  train_steps: 250000
  inner_steps: 1
  train_batch_size: 120
  test_size: 1000
  test_batch_size: 1000
  learning_rate: 0.0001
  log_step: 10000
  aug_factor: 1
model_params:
  ensemble: learn  # [learn, no]
  ensemble_size: 1
  encoder_mask: False
  penalty: -1
  local_size: [100]
  embedding_dim: 128
  encoder_layer_num: 6
  head_num: 8
  qkv_dim: 16
  logit_clipping: 50
  ff_hidden_dim: 512